compilation failed, in this form
-- The C compiler identification is unknown
substituteStream(): WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file './manual.md')
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /nix/store/y7vxbacjbv86xj4vr94j5prps38n4c8x-ccache-links-wrapper-4.9.1/bin/gcc
-- Check for working C compiler: /nix/store/y7vxbacjbv86xj4vr94j5prps38n4c8x-ccache-links-wrapper-4.9.1/bin/gcc - broken
CMake Error at /nix/store/nj0g2xkxgxhcapg2xs8qi80h8fgkywr3-cmake-3.28.3/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/nix/store/y7vxbacjbv86xj4vr94j5prps38n4c8x-ccache-links-wrapper-4.9.1/bin/gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/build/source/build/CMakeFiles/CMakeScratch/TryCompile-zOb8wd'

    Run Build Command(s): /nix/store/nj0g2xkxgxhcapg2xs8qi80h8fgkywr3-cmake-3.28.3/bin/cmake -E env VERBOSE=1 /nix/store/3wwka0sn2h96cmqxyclj2vba26a5sk1s-gnumake-4.4.1/bin/make -f Makefile cmTC_219da/fast
    /nix/store/3wwka0sn2h96cmqxyclj2vba26a5sk1s-gnumake-4.4.1/bin/make  -f CMakeFiles/cmTC_219da.dir/build.make CMakeFiles/cmTC_219da.dir/build
    make[1]: Entering directory '/build/source/build/CMakeFiles/CMakeScratch/TryCompile-zOb8wd'
    Building C object CMakeFiles/cmTC_219da.dir/testCCompiler.c.o
    /nix/store/y7vxbacjbv86xj4vr94j5prps38n4c8x-ccache-links-wrapper-4.9.1/bin/gcc    -o CMakeFiles/cmTC_219da.dir/testCCompiler.c.o -c /build/source/build/CMakeFiles/CMakeScratch/TryCompile-zOb8wd/testCCompiler.c
    failing on purpose, to detect is this is being used instead: ./nixos/modules/programs/ccache.nix
    make[1]: *** [CMakeFiles/cmTC_219da.dir/build.make:78: CMakeFiles/cmTC_219da.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/build/source/build/CMakeFiles/CMakeScratch/TryCompile-zOb8wd'
    make: *** [Makefile:127: cmTC_219da/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)

-- Configuring incomplete, errors occurred!
error: builder for '/nix/store/wf710lkmyfp5wrn2vwfdhx69pab6k30l-keepassxc-2.7.7.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/3022zcxbd63wnfj0c77g4vl0f09wkhs6-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5ap4iqimqran8g9sln80d5yl5spqbl0x-nixos-system-vbox1-24.05.git.a36542028009M.drv' failed to build

real    0m16.992s
user    0m0.010s
sys     0m0.005s